apiVersion: email.mailerlite.io/v1
kind: Email
metadata:
  labels:
    app.kubernetes.io/name: mailerlite-sre-assignment
    app.kubernetes.io/managed-by: kustomize
  name: email-sample
spec:
  # TODO(user): Add fields here
