apiVersion: email.mailerlite.io/v1
kind: EmailSenderConfig
metadata:
  labels:
    app.kubernetes.io/name: mailerlite-sre-assignment
    app.kubernetes.io/managed-by: kustomize
  name: emailsenderconfig-sample
spec:
  # TODO(user): Add fields here
